Bugfix/project stucture and dto models fix
alexandrakrupko/weather-reporter pull request #2
Opened 2024-04-18 12:38 UTC by alexandrakrupko

2024-04-18 12:41 UTC, alexandrakrupko commented on src/main/java/weather/controller/WeatherController.java
> +                .orElseThrow(() -> new ControllerException("Fail to process request", HttpStatus.NOT_FOUND));
На последующих этапах будет добавлен global exception handler, он будет ловить ControllerException и в ResponseEntity отдавать ErrorResponse

2024-04-19 07:39 UTC, Zuevsky commented on src/main/java/weather/controller/WeatherController.java
> +    private final WeatherResponseMapper weatherResponseMapper;
Логика с маппингом сущностей должна находится в сервисном слое

2024-04-19 07:45 UTC, Zuevsky commented on src/main/java/weather/exception/ControllerException.java
> +public class ControllerException extends Exception {
Кастомный ексепшн лучше называть сразу с бизнес смыслом. В данном случае ошибка будет вроде cityNotFound / incorrectCityName или на твой выбор. 
Ексепшн относится не к слою, а к бизнес логике.

2024-04-19 07:48 UTC, Zuevsky commented on src/main/java/weather/mapper/TemperatureResponseMapper.java
> +public interface TemperatureResponseMapper {
Любые мапперы - это сервисные классы. Для них излишней будет абстракция в виде интерфейса(API).
Достаточно сделать просто класс с публичными методами маппинга (один класс - для одной сущности).
Либо можно и вовсе сделать его ютилом -> класс с приватным конструктором и статическими методами маппинга (чтобы не инжектить как компонент).

2024-04-19 07:54 UTC, Zuevsky commented on src/main/java/weather/exception/ControllerException.java
> +    private final HttpStatus status;
В ексепшене не нужен статус, он добавляется для респонса. Здесь оставляем только сообщение.

2024-04-19 07:56 UTC, Zuevsky requested changes
И еще один важный вопрос:
Почему кастомные ексепшены лучше наследовать от РанТаймЕксепшн, а не просто Ексепшн? 
Ответ напиши своими словами в чат и поправь в коде

2024-04-19 08:29 UTC, alexandrakrupko commented on src/main/java/weather/mapper/TemperatureResponseMapper.java
> +public interface TemperatureResponseMapper {
+

2024-04-19 08:30 UTC, alexandrakrupko commented on src/main/java/weather/mapper/TemperatureResponseMapper.java
> +public interface TemperatureResponseMapper {
++

2024-04-19 08:44 UTC, alexandrakrupko commented on src/main/java/weather/controller/WeatherController.java
> +    private final WeatherResponseMapper weatherResponseMapper;
++

2024-04-19 08:45 UTC, alexandrakrupko commented on src/main/java/weather/exception/ControllerException.java
> +public class ControllerException extends Exception {
++

2024-04-19 08:46 UTC, alexandrakrupko commented on src/main/java/weather/exception/ControllerException.java
> +    private final HttpStatus status;
++

2024-04-19 09:34 UTC, closed without merging