feat: weather service receives data from external API
alexandrakrupko/weather-reporter pull request #4
Opened 2024-04-19 12:35 UTC by alexandrakrupko

RestClient is used to interact with OpenWeather API.

2024-04-22 07:58 UTC, Zuevsky requested changes

2024-04-22 07:58 UTC, Zuevsky commented on README.adoc
> +* Add an environment variable in the format: `integration.openweather.api-key={API key}` +
А чего ты сразу в проперти не добавила ключ, или он меняется через какое-то время?

2024-04-22 07:58 UTC, Zuevsky commented on src/main/java/weather/integration/openweather/OpenWeatherClient.java
> +        } catch (RuntimeException e) {
Эта апиха кидает какие-то кастомные ексепшены? 
Например: сервис временне недоступен, неправильный реквест и т.д. 
Можно будет под них создать свои бизнес ексепшены, чтобы не мапить все в ситинотфаунд

2024-04-22 07:58 UTC, Zuevsky commented on src/main/java/weather/integration/openweather/OpenWeatherClient.java
> +            throw new CityNotFoundException("Fail to get weather data for city \"%s\"".formatted(city));
String.formatted - это аналог String.format ? я просто не шарю

2024-04-22 07:58 UTC, Zuevsky commented on src/main/java/weather/integration/openweather/OpenWeatherJsonParser.java
> +        JsonNode jsonNode = objectMapper.readTree(json);
А зачем ты читаешь сначала JsonNode и распаршиваешь ее в дто? 
Можно же сделать сразу objectMapper.readValue(json, TemperatureDto.class)
Или нет?

2024-04-22 07:58 UTC, Zuevsky commented on src/main/java/weather/service/WeatherServiceImpl.java
> +                .orElseThrow(() -> new RequestProcessingException("Fail to get weather data")));
Ты же уже кидаешь ексепшн в случае ошибки соединения в клиенте, зачем здесь дублировать?

2024-04-22 07:58 UTC, Zuevsky commented on src/main/java/weather/controller/WeatherController.java
> +                .orElseThrow(() -> new RequestProcessingException("Fail to process request"));
Опять дубликат, ты же кидаешь ошибку в клиенте, зачем еще в сервисе и в контроллере?

2024-04-22 09:03 UTC, alexandrakrupko commented on src/main/java/weather/integration/openweather/OpenWeatherClient.java
> +            throw new CityNotFoundException("Fail to get weather data for city \"%s\"".formatted(city));
да, так запись короче получается

2024-04-22 11:02 UTC, alexandrakrupko commented on src/main/java/weather/integration/openweather/OpenWeatherJsonParser.java
> +        JsonNode jsonNode = objectMapper.readTree(json);
Чтобы использовать objectMapper.readValue и читать срузу в объект, по умолчанию все поля json должны маппиться на поля объекта. Я пробовала использовать аннтоацию @JsonProperty над полями класса, чтобы явно указать, какие поля json маппить с полем объекта. + аннотация @JsonIgnoreProperties(ignoreUnknown = true) над классом DTO, т.к. по умолчанию Jackson пытается вообще все поля замэпить на поля объекта.

Но проблема возникла с TemperatureDto, т.к. нужно замэпить вложенные json свойства на поля объекта. @JsonProperty не позволяет такого сделать. Один из способов решения: завести в TemperatureDto "подклассы" для вложенных полей, это очень усложняет восприятие Dto.

Может ты знаешь другой способ мэппинга вложегнных свойств из json?

2024-04-22 12:59 UTC, alexandrakrupko commented on README.adoc
> +* Add an environment variable in the format: `integration.openweather.api-key={API key}` +
++

2024-04-22 12:59 UTC, alexandrakrupko commented on src/main/java/weather/integration/openweather/OpenWeatherClient.java
> +        } catch (RuntimeException e) {
++

2024-04-22 12:59 UTC, alexandrakrupko commented on src/main/java/weather/service/WeatherServiceImpl.java
> +                .orElseThrow(() -> new RequestProcessingException("Fail to get weather data")));
++

2024-04-22 12:59 UTC, alexandrakrupko commented on src/main/java/weather/controller/WeatherController.java
> +                .orElseThrow(() -> new RequestProcessingException("Fail to process request"));
++

2024-04-22 15:19 UTC, Zuevsky requested changes

2024-04-22 15:19 UTC, Zuevsky commented on src/main/java/weather/integration/openweather/OpenWeatherClient.java
> +                        if (statusCode.isSameCodeAs(HttpStatusCode.valueOf(404))) {
может получится симпатичнее переписать на switch?

2024-04-22 15:19 UTC, Zuevsky commented on src/main/java/weather/controller/WeatherController.java
> +                .orElseThrow(() -> new CityNotFoundException("City not found: '%s'".formatted(city)));
Все равно не понимаю, если ты прокидываешь ошибки в клиенте, зачем здесь оставлять CityNotFoundException.
Может я туплю, объясни плиз

2024-04-22 15:47 UTC, alexandrakrupko commented on src/main/java/weather/controller/WeatherController.java
> +                .orElseThrow(() -> new CityNotFoundException("City not found: '%s'".formatted(city)));
Изначально планировала в контроллере выставлять статус в ResponseEntity на основании Optional (если пустой, то 404). То есть контракт приложения такой: контроллер отвечает за бизнес-ошибку CityNotFoundException, а у сервисов могут возникнуть свои runtime exception.
По ТЗ нужно ловить ошибку в global exсeption handler, поэтому контроллер ее пробрасывает, а не возвращает ResponseEntity со статусом.

И еще читала в какой-то статье, что лучше избегать пробрасывания ошибок, где это возможно, чтобы быстрее работала программа.

Тогда, если я переношу выброс этой ошибки в OpeWeatherClient, то нужно везде убирать Optional из сигнатуры серсисов. Как тогда поступать?

2024-04-22 17:13 UTC, alexandrakrupko commented on src/main/java/weather/exception/GlobalExceptionHandler.java
> +                .status(HttpStatus.INTERNAL_SERVER_ERROR)
@Zuevsky Нужно ли в ErrorResponse поле со статусом, если мы его передаем в ResponseEntity (в хедерах)?

2024-04-22 17:17 UTC, alexandrakrupko commented on src/main/java/weather/exception/GlobalExceptionHandler.java
@Zuevsky Правильно ли лежит GlobalExceptionHandler? Вопрос возник, потому что проставлять статусы в респонс - это зона ответственности контроллера (т.е. был вариант положить его в папку controller)

2024-04-23 08:16 UTC, Zuevsky approved these changes

2024-04-23 08:16 UTC, Zuevsky commented on src/main/java/weather/exception/GlobalExceptionHandler.java
Лежит правильно, в пакете с исключениями

2024-04-23 08:16 UTC, Zuevsky commented on src/main/java/weather/exception/GlobalExceptionHandler.java
> +                .status(HttpStatus.INTERNAL_SERVER_ERROR)
Да, нужен

2024-04-23 08:16 UTC, Zuevsky commented on src/main/java/weather/integration/openweather/OpenWeatherClient.java
> +            if (!response.hasBody()) {
Мне не очень нравится как тут написан весь этот трай кетч флоу, очень громоздко, но я пока не придумал, как это можно упростить, так что заливай так, потом может переделаем.

2024-04-23 16:08 UTC, merged