Test/tests and logging
alexandrakrupko/weather-reporter pull request #7
Opened 2024-05-15 10:05 UTC by alexandrakrupko

2024-05-15 10:06 UTC, alexandrakrupko commented on src/test/java/weather/IntegrationTest.java
> +    @SuppressWarnings("resource")
здесь аннотация стоит, т.к. подвечивает try-with-resources, но контенейры сами закрываются после того, как тесты отрабатывают

2024-05-16 12:42 UTC, Zuevsky requested changes

2024-05-16 12:42 UTC, Zuevsky commented on src/test/java/weather/service/WeatherServiceImplIntegrationTest.java
> +    private static class Tool {
Для тестов если нужны статические данные, то их выносят в ютилзы для тестов. Можешь  создавать ютилз классы под каждое доменное направление тестов, то есть отталкиваясь от логики

2024-05-22 08:26 UTC, Zuevsky approved these changes

2024-05-23 15:16 UTC, merged